### ISSUE TITLE
关于外部异常捕获的问题

### ISSUE THREAD

**Issue by TOP-LH** [feiniaojin/graceful-response#20]
![image](https://github.com/feiniaojin/graceful-response/assets/49888630/53c66e3c-3546-4234-bb84-92dc66994343)
如图所示, 现在捕获外部需要使用@ExceptionAliasFor这个异常, 但假如说有一些异常他是通过异常和异常中的编码一起判断的, 该如何分别捕获呢? 例如sa-token这种
![image](https://github.com/feiniaojin/graceful-response/assets/49888630/4014b89f-03d7-4ace-a237-b6c92d7e4930)

**Comment by feiniaojin** [comment]
这个地方属于鉴权的逻辑，在实际中鉴权逻辑还没走到具体的接口内部，完全可以由使用者在自己的拦截器里面作处理的。

**Comment by TOP-LH** [comment]
> 这个地方属于鉴权的逻辑，在实际中鉴权逻辑还没走到具体的接口内部，完全可以由使用者在自己的拦截器里面作处理的。

意思就是我自己写一个异常拦截器去捕获吗？

**Comment by feiniaojin** [comment]
是的，你不可能在每个方法里面做这个事情，鉴权逻辑应该和业务方法解耦，你应该重写sa-token的拦截器。---- 回复的原邮件 ***@***.***>发送日期2023年07月20日 17:57 ***@***.***> ***@***.***>,State ***@***.***>主题Re: [feiniaojin/graceful-response] 关于外部异常捕获的问题 (Issue #20)

这个地方属于鉴权的逻辑，在实际中鉴权逻辑还没走到具体的接口内部，完全可以由使用者在自己的拦截器里面作处理的。

意思就是我自己写一个异常拦截器去捕获吗？

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/feiniaojin/graceful-response/issues/20#issuecomment-1643628437",
"url": "https://github.com/feiniaojin/graceful-response/issues/20#issuecomment-1643628437",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
